title: Aptico Documentation
description: Agentic AI Engineering with Aptico CLI
url: "https://apyhtml20.github.io"
baseurl: "/Docs.io"
theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag